### ISSUE TITLE
Slava_gey

### ISSUE THREAD

**Issue by olandreievvirtru** [electricSemyon/shitty-linked-lists#1]
https://github.com/electricSemyon/shitty-linked-lists/blob/4fd9875a0236e6f3a75355d0daeb773245ecf1ad/LinkedLists/Program.cs#L23
ну можно было и билдер для этой использовать.
```

            processor.DeleteStringEntries(firstEntryWithTwoSameLetters)
            .OmitWordsWithLetterDuplicates("dolor")
            .RemoveOrs()
            .InsertOrs()
            .RemoveWordsWithLessThanFourCharacters()
            .ProcessWordsWithMoreThanFourCharacters()
```
и может параметры добвыить чтоб 4 не хардкодить
```
ProcessWordsWithMoreThanFourCharacters
```

- [сделай приватным](https://github.com/electricSemyon/shitty-linked-lists/blob/master/LinkedLists/TextProcessor.cs#L31)
-  Юзай [StringBuilder](https://github.com/electricSemyon/shitty-linked-lists/blob/master/LinkedLists/CircularDoublyLinkedList.cs#L70) для конкатенации строк
- можно было и [итератор](https://stackoverflow.com/questions/348964/how-to-use-foreach-keyword-on-custom-objects-in-c-sharp) реализовать вместо своих [ForEach](https://github.com/electricSemyon/shitty-linked-lists/blob/master/LinkedLists/CircularDoublyLinkedList.cs#L31)

**Comment by slaviqueue** [comment]
@olandreievvirtru спасибо, буду чинить! 💯
